name: ccrhack
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_staggered_grid_view: ^0.3.0
  shared_preferences: ^0.5.6+3
  image_picker: ^0.6.4
  simple_animations: ^1.3.11
  font_awesome_flutter: ^8.8.1
  outline_material_icons: ^0.1.0
  sliding_up_panel: ^1.0.2
  carousel_slider: ^2.1.0
  #url_launcher: ^5.4.7
  shimmer: ^1.1.1
  image_cropper: ^1.2.2
  #image_editor_pro: ^1.0.6
  url_launcher: ^5.4.10
  zoom_widget: ^0.1.3
  #image_picker: ^0.6.3+1
  path_provider: ^1.6.8
  image_gallery_saver: ^1.2.2
  permission_handler: ^5.0.0+hotfix.6
  dio: ^3.0.9
  screenshot: ^0.1.1
  signature: ^3.1.1
  flutter_colorpicker: ^0.3.4
  google_fonts: ^1.1.0
  photo_view: ^0.9.2
  flutter_datetime_picker: ^1.3.8 #MIT LICENSE
  auto_size_text: ^2.1.0 #MIT LICENSE
  jiffy: ^3.0.1 #MIT LICENSE
  async: ^2.4.1
  # cached network image
  cached_network_image: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: ^0.12.1 
  provider: ^4.0.4
  confetti: ^0.5.2
  google_maps_flutter: ^0.5.28+1  
  location: ^3.0.2
  geolocator: ^5.3.1
  slider_button: ^0.5.0
  lottie: ^0.3.6
  google_sign_in: ^4.5.1
  apple_sign_in: ^0.1.0
  firebase_auth: ^0.15.5+3
  introduction_screen: ^1.0.8
  animated_text_kit: ^2.2.0
  flutter_google_places: ^0.2.5
  google_maps_webservice: ^0.0.16
  fit_kit: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/img/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
